### PR TITLE
Several UI fixes and alignments for desktop and mobile views

### PR DESCRIPTION
**Pull request by ronilaukkarinen**
Hello,

This PR fixes some alignment issues for posters and settings as well as spacing between pills and buttons, broken import view. Tested working, here's some screenshots:

screenshot
screenshot

Let me know what you think!

### CODE REVIEW

**Comment by ronilaukkarinen** [comment]
On the side note: buttons still need some work on mobile, but I'm mostly concentrating on Desktop views right now.

**Comment by barbequesauce** [comment]
Looks good to me - @ellnic @scambra can you take a look please?

**Comment by barbequesauce** [comment]
And thanks for contributing!

**Comment by ronilaukkarinen** [comment]
Awesome, thanks!

**Pull request merged**
