### PR TITLE
Fix for the modal drop downs going black (and other CSS)

### PR DESCRIPTION
**Pull request by ellnic**
Alters the colour of the text to #EBEBEB so the drop down doesn't appear to go black when the focus changes.

### CODE REVIEW

**Comment by barbequesauce** [comment]
These good to go?

**Comment by ellnic** [comment]
Not yet, relates to #65 - nearly done though.

**Comment by ellnic** [comment]
Should be good now.

**Comment by barbequesauce** [comment]
Thanks!

**Pull request merged**
