### PR TITLE
Fix gap between posters

### PR DESCRIPTION
**Pull request by ronilaukkarinen**
This PR fixes the huge gap between posters.

### CODE REVIEW

**Comment by barbequesauce** [comment]
Thanks @ronilaukkarinen ! The change makes sense to me, but I'm not a css guy - @ellnic this is your territory...

**Comment by ronilaukkarinen** [comment]
Well, I'm a CSS guy :) Wasn't sure if it was a matter of taste or a bug but it kinda bothered me so I decided to go and do a PR. I'd like to contribute in the future on CSS/JS side as well if I happen to encounter issues style-wise in the future.

Of course you should check the PR out, but let me explain first. I feel like this looks much better

(in PR)

screenshot

than this (in current branch)

screenshot

What do you think?

**Comment by ellnic** [comment]
Hi @ronilaukkarinen thanks for submitting this. I agree completely, it looks much better like this. I have a CSS list as long as my arm, but I am still altering default themes so they've all been pushed back for now. Your PR also fixes the drop down menu being cut off when there is only 1 line of results - fantastic.

I am not a CSS guy either, I'm just making this up as I go along ;) So please feel free to scrutinize and submit anything else you feel would improve the CSS - we are happy to take PRs :)

**Comment by ronilaukkarinen** [comment]
Thanks for the warm feedback and merging my PR! I will definitely contribute more if there's need. Have a nice xmas! 👍

**Comment by ellnic** [comment]
And you, thanks again :)

**Pull request merged**
